######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 27 18:51:52 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT -=  gui
QT += core
CONFIG += c++11
unix: QMAKE_CXXFLAGS += -std=c++0x

OBJECTS_DIR = ./tmp
MOC_DIR = ./moc

# Input
SOURCES += main.cpp

include(../qtservice/qt-solutions/qtservice/src/qtservice.pri)
